server:
  port: 8892

spring:
  datasource:
    # 数据源1配置 (yunxin_recovery数据库)
    db1:
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        url: jdbc:mysql://127.0.0.1:3306/yunxin_recovery?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&connectTimeout=5000
        username: root
        password: xu20141210chen
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 连接池配置
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000

    # 数据源2配置 (test数据库)
    db2:
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        url: jdbc:mysql://127.0.0.1:4407/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&connectTimeout=5000
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 连接池配置
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000

mybatis:
  mapper-locations: classpath:com/conmu/sms/dao/mapper/**/*.xml

